### ISSUE TITLE
Can you support LibVLCSharp.avalonia or libmpv.avalonia players in godot4?

### ISSUE THREAD

**Issue by youfch** [MrJul/Estragonia#10]
I tried this many times, and with each run a new window would open to play the video
![image](https://github.com/MrJul/Estragonia/assets/97601975/b30dd2fa-0630-4436-9168-d463f53b62b1)

**Comment by youfch** [comment]
I tried to use cef to play videos or display web pages and finally tried to only support dotnetbrowser.avalonia but the license was too expensive

**Comment by ShadowMarker789** [comment]
I know that LibVLCSharp uses a WinFormsHost to host the video, so it's not a surprise that it spawns in a separate window.

**Comment by MrJul** [comment]
As mentioned, LibVLCSharp can't be supported because it uses a native control.
LibMpv.Avalonia uses OpenGL, and can't work with the Vulkan renderer.

If possible, try to use Godot's [video player](https://docs.godotengine.org/en/stable/tutorials/animation/playing_videos.html).
