### ISSUE TITLE
Estragonia specifically requires Avalonia.Skia v 11.0.5 

### ISSUE THREAD

**Issue by ShadowMarker789** [MrJul/Estragonia#11]
![image](https://github.com/MrJul/Estragonia/assets/37165910/b141898b-4891-4218-8061-17108a4ece73)

Specifically requiring Avalonia.Skia 11.0.5 means I cannot upgrade the version of Avalonia without lots of warnings from the build pipeline. 

Is there a reason you've stated you wanted Skia 11.0.5 specifically, and not >= 11.0.5?

**Comment by MrJul** [comment]
v1.1.0 is released, which targets Avalonia 11.0.10.
A preview version is coming for Avalonia 11.1 beta/rc.
