### ISSUE TITLE
Unable to use Estragonia on macOS due to Vulkan dependency

### ISSUE THREAD

**Issue by waterpare833** [MrJul/Estragonia#13]
Environment:
- Operating System: macOS M3 Pro
- Godot version: 4.2.2

Issue Description:
When attempting to run the Estragonia sample project on macOS, an error occurs stating that the Vulkan DLL cannot be loaded. This appears to be due to macOS not natively supporting Vulkan.

Error Message:
ERROR: System.DllNotFoundException: Unable to load shared library 'libvulkan' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable:

Steps to Reproduce:
1. Clone the Estragonia sample project
2. Open the project in Godot on macOS
3. Attempt to run the project
4. Observe the Vulkan-related error

Question:
Is it currently possible to use Estragonia on macOS? If not, are there any plans to support macOS in the future?

Thank you for your time and consideration.

**Comment by candhub** [comment]
I'm in same trouble. I really wanna fine right answer about this problem.

**Comment by youfch** [comment]
linux上遇到了一样的报错，我记得好像是指向sudo ln -s /usr/lib/x86_64-linux-gnu/libvulkan.so.1 /usr/lib/x86_64-linux-gnu/libvulkan.so解决了，不过macos没用过

**Comment by lightway82** [comment]
It would be possible to use [MoltenVK](https://github.com/KhronosGroup/MoltenVK) instead of libvulkan for macos.

**Comment by MrJul** [comment]
I've updated the Vulkan loading logic to match the one used by Godot/Volk:
Estragonia: https://github.com/MrJul/Estragonia/commit/2e5b4183df7562624088b9026432b8fec8c3665c
Godot: https://github.com/godotengine/godot/blob/master/thirdparty/volk/volk.c#L71-L115

That said, as mentioned above, you probably need MoltenVK installed on macOS as I believe the Vulkan loader is statically linked into Godot's macOS build, so we can't access it directly.

Note that I don't have much experience building and using Godot with macOS, so feel free to correct me or reopen the issue if needed.

**Comment by waterpare833** [comment]
> It would be possible to use [MoltenVK](https://github.com/KhronosGroup/MoltenVK) instead of libvulkan for macos.

I've installed MoltenVK using Homebrew, but Godot isn't able to locate the MoltenVK dynamic library (DLL). Do I need to make additional configurations for Godot to recognize and use MoltenVK instead of libvulkan? If so, what steps are necessary to ensure Godot can find and use MoltenVK correctly on macOS?

**Comment by waterpare833** [comment]
> I've updated the Vulkan loading logic to match the one used by Godot/Volk: Estragonia: [2e5b418](https://github.com/MrJul/Estragonia/commit/2e5b4183df7562624088b9026432b8fec8c3665c) Godot: https://github.com/godotengine/godot/blob/master/thirdparty/volk/volk.c#L71-L115
> 
> That said, as mentioned above, you probably need MoltenVK installed on macOS as I believe the Vulkan loader is statically linked into Godot's macOS build, so we can't access it directly.
> 
> Note that I don't have much experience building and using Godot with macOS, so feel free to correct me or reopen the issue if needed.

I've installed MoltenVK using Homebrew, but Godot isn't able to locate the MoltenVK dynamic library (DLL). Do I need to make additional configurations for Godot to recognize and use MoltenVK instead of libvulkan? If so, what steps are necessary to ensure Godot can find and use MoltenVK correctly on macOS?
