### ISSUE TITLE
Allow click through on transparent areas

### ISSUE THREAD

**Issue by dotlogix** [MrJul/Estragonia#14]
Hey there I just found out, that there is an issue if you overlay an Avalonia control with transparency on top of other Godot nodes.

I think it would be useful to override _HasPoint on the AvaloniaControl and execute a hit test against Avalonia. This way you can stack multiple layers of Avalonia/Godot controls on top of each other.

It is actually very simple to do using this method:
```cs
public override bool _HasPoint(Vector2 point)
{
    return Control?.InputHitTest(point.ToAvaloniaPoint()) is not null;
}
```

**Comment by MrJul** [comment]
Thanks for the suggestion! I've implemented it on v1.2.0.
Don't hesitate to open a PR next time :)
