### ISSUE TITLE
Samples update to .net 8 / godot 4.3

### ISSUE THREAD

**Issue by orosbogdan** [MrJul/Estragonia#16]
Since godot 4.3 is out, it would be nice if this plugin would support .net 8 and godot 4.3 and the samples would be updated to the latest versions of these two.

**Comment by dotlogix** [comment]
What do you mean by this?
I use it with .Net 9 and 4.3 and that perfectly works as expected :)

**Comment by MrJul** [comment]
Godot has been updated to 4.3 and Avalonia to 11.1.3 in Estragonia 1.2.0.

It still targets .NET 6.0 to match GodotSharp, but should be usable without any issues on .NET 7, 8 and 9, as mentioned above by dotlogix.
