### ISSUE TITLE
I would like to inquire about the Avalonia version update.

### ISSUE THREAD

**Issue by kdi0905** [MrJul/Estragonia#24]
I am aware that Avalonia has been updated to version 11.2.1. Would it be possible to perform an update to this latest version?

Also, when a newer version is released in the future, would it be possible to use it by just updating Avalonia?

**Comment by MrJul** [comment]
I've just released v1.3.0 with Avalonia 11.2.1.

No, it isn't possible to update Avalonia independently. As stated in https://github.com/MrJul/Estragonia/blob/main/docs/toknow.md, Estragonia uses some Avalonia's internal platform APIs, which may change in minor versions.

That isn't just theoretical. If you take a look at commit https://github.com/MrJul/Estragonia/commit/ef4d0acea489c8e1e1bc78971b82cf268239084c where Avalonia is updated to 11.2.1, you'll notice that two new members from `ITopLevelImpl` needed to be implemented. Without those, you'll simply encounter a crash.
