### ISSUE TITLE
Possible to use Avalonia's StorageProvider to open file picker?

### ISSUE THREAD

**Issue by MechWarrior99** [MrJul/Estragonia#8]
Hey, this has been working fantastically so far! 
I was wondering though if it would be possible to add support for opening the file picker via the StorageProvider class from Avalonia?
I am assuming it doesn't right now because the platform is not being registered as a desktop with Avalonia?
([Avalonia docs for storage provider platforms](https://docs.avaloniaui.net/docs/concepts/services/storage-provider#platform-compatibility))

Totally get if it isn't really feasible. If that is the case, it might be wroth mentioning in the `to know` section on github.

Thanks!

**Comment by MrJul** [comment]
`IStorageProvider` has been implemented in v1.1.0 (by using Godot's `FileDialog`).
